name: Release Please

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  release-please:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures full history, tags, and commits are available

      - name: Log New Commits
        run: |
          echo "=== Latest Release Tag on Main ==="
          git describe --tags $(git rev-list --tags --max-count=1)

          echo "=== Commits Since Last Tag ==="
          LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          git log $LAST_TAG..develop --oneline

      - name: Release Please
        uses: googleapis/release-please-action@v3.4.0
        with:
          token: ${{ secrets.ORG_GITHUB_WRITE_TOKEN }}
          release-type: node # Use node instead of simple
          default-branch: main
          bump-minor-pre-major: true
          changelog-types: |
            [
              {
                "type": "feat",
                "section": "Features"
              },
              {
                "type": "fix",
                "section": "Bug Fixes"
              },
              {
                "type": "perf",
                "section": "Performance Improvements"
              },
              {
                "type": "revert",
                "section": "Reverts"
                },
              {
                "type": "docs",
                "section": "Documentation",
                "hidden": true
              },
              {
                "type": "style",
                "section": "Styles",
                "hidden": true
              },
              {
                "type": "chore",
                "section": "Miscellaneous Chores",
                "hidden": true
              },
              {
                "type": "refactor",
                "section": "Code Refactoring",
                "hidden": true
              },
              {
                "type": "test",
                "section": "Tests",
                "hidden": true
              },
              {
                "type": "build",
                "section": "Build System",
                "hidden": true
              },
              {
                "type": "ci",
                "section": "Continuous Integration",
                "hidden": true
              }
            ]
