name: Release Please
on:
  push:
    branches:
      - develop

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.ORG_GITHUB_WRITE_TOKEN }}
          release-type: simple
          default-branch: main
          bump-minor-pre-major: Yes
          changelog-types: |
            [
              {
                "type": "feat",
                "section": "Features"
              },
              {
                "type": "fix",
                "section": "Bug Fixes"
              },
              {
                "type": "perf",
                "section": "Performance Improvements"
              },
              {
                "type": "revert",
                "section": "Reverts"
              },
              {
                "type": "docs",
                "section": "Documentation",
                "hidden": true
              },
              {
                "type": "style",
                "section": "Styles",
                "hidden": true
              },
              {
                "type": "chore",
                "section": "Miscellaneous Chores",
                "hidden": true
              },
              {
                "type": "refactor",
                "section": "Code Refactoring",
                "hidden": true
              },
              {
                "type": "test",
                "section": "Tests",
                "hidden": true
              },
              {
                "type": "build",
                "section": "Build System",
                "hidden": true
              },
              {
                "type": "ci",
                "section": "Continuous Integration",
                "hidden": true
              }
            ]
