name: Release Please

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  release-please:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release Please
        uses: googleapis/release-please-action@v3.4.0
        with:
          token: ${{ secrets.ORG_GITHUB_WRITE_TOKEN }}
          release-type: simple
          default-branch: main
          bump-minor-pre-major: true
          changelog-types: |
            [
              {
                "type": "feat",
                "section": "Features"
              },
              {
                "type": "fix",
                "section": "Bug Fixes"
              },
              {
                "type": "perf",
                "section": "Performance Improvements"
              },
              {
                "type": "revert",
                "section": "Reverts"
              },
              {
                "type": "docs",
                "section": "Documentation",
                "hidden": true
              },
              {
                "type": "style",
                "section": "Styles",
                "hidden": true
              },
              {
                "type": "chore",
                "section": "Miscellaneous Chores",
                "hidden": true
              },
              {
                "type": "refactor",
                "section": "Code Refactoring",
                "hidden": true
              },
              {
                "type": "test",
                "section": "Tests",
                "hidden": true
              },
              {
                "type": "build",
                "section": "Build System",
                "hidden": true
              },
              {
                "type": "ci",
                "section": "Continuous Integration",
                "hidden": true
              }
            ]
