name: Release Please

on:
  push:
    branches:
      - develop

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # to get tag information

      - name: Release Please # on develop branch with tags from main
        uses: GoogleCloudPlatform/release-please-action@v3.2.5
        with:
          token: ${{ secrets.ORG_GITHUB_WRITE_TOKEN }}
          release-type: simple
          bump-minor-pre-major: true
          default-branch: main
          fork: true
          changelog-types: |
            [
              {
                "type": "feat",
                "section": "Features"
              },
              {
                "type": "fix",
                "section": "Bug Fixes"
              },
              {
                "type": "perf",
                "section": "Performance Improvements"
              },
              {
                "type": "revert",
                "section": "Reverts"
              },
              {
                "type": "docs",
                "section": "Documentation",
                "hidden": true
              },
              {
                "type": "style",
                "section": "Styles",
                "hidden": true
              },
              {
                "type": "chore",
                "section": "Miscellaneous Chores",
                "hidden": true
              },
              {
                "type": "refactor",
                "section": "Code Refactoring",
                "hidden": true
              },
              {
                "type": "test",
                "section": "Tests",
                "hidden": true
              },
              {
                "type": "build",
                "section": "Build System",
                "hidden": true
              },
              {
                "type": "ci",
                "section": "Continuous Integration",
                "hidden": true
              }
            ]
